package com.ticketopia.daos;

public class UserDaoImpl {
	// create account
		// takes in:
			// display name
			// first name
			// last name
			// address
			// email
			// password
		// userId will be autogenerated
		// adds this to database
	
	// add payment method
		// takes in:
			// userId
			// card number
			// security code
			// expiration
			// billing address
		//adds this to database
	
	// adjust role
		// takes in userId and desired role
		// if upgrading, make sure there is payment info on file
		// if downgrading, simply adjust role
}
