package com.ticketopia.daos;

public interface UserDao {
	// create account
			// takes in:
				// display name
				// first name
				// last name
				// address
				// email
				// password
			// userId will be autogenerated
			// adds this to database
		
		// add payment method
			// takes in:
				// userId
				// card number
				// security code
				// expiration
				// billing address
			//adds this to database
		
		// adjust role
			// takes in userId and desired role
			// if upgrading, make sure there is payment info on file
			// if downgrading, simply adjust role
		
		// change password
			// verify password first
			// save new password to the database
		
		// remove payment method
			// if premium user, must downgrade
			// removes payment method from database
}
